- name: Install basic packages on Ubuntu
  become: true
  block:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required apt packages
      apt:
        name:
          - curl
          - vim
          - git
          - wget
          - build-essential
          - software-properties-common
          - sudo
          - unzip
          - lsb-release
          - ca-certificates
          - jq
        state: present
        update_cache: yes