- name: Install Docker
  become: true
  block:
  - name: Install required apt packages
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      state: present
      update_cache: yes

  - name: Add Docker’s official GPG key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker APT repository
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
      state: present

  - name: Update APT cache
    apt:
      update_cache: yes

  - name: Install Docker Engine
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      state: present

  - name: Add user to docker group
    become: true
    user:
      name: "{{ ansible_user_id }}"
      groups: docker
      append: yes
