- name: Setup Development Environment
  hosts: localhost
  gather_facts: yes
  vars_files:
    - vars.yml
  tasks:
    # Default stuff
    - import_tasks: tasks/basic.yml
      tags:
        - default
        - basic
    - import_tasks: tasks/directories.yml
      tags:
        - default
        - directories
    - import_tasks: tasks/aliases.yml
      tags:
        - default
        - aliases
    - import_tasks: tasks/zsh.yml
      tags:
        - default
        - zsh
    - import_tasks: tasks/chrome.yml
      tags:
        - default
        - chrome
    # Docker  
    - import_tasks: tasks/docker.yml
      tags:
        - docker
    # Java specific
    - name: Install IntelliJ Ultimate
      import_tasks: tasks/jetbrains_installation.yml
      vars:
        download_url: "{{ intellij_ultimate_download_url }}"
        target_installation_folder: "{{ intellij_ultimate_folder }}"
      tags:
        - java
        - intellij-ultimate
    - name: Install IntelliJ Community Edition
      import_tasks: tasks/jetbrains_installation.yml
      vars:
        download_url: "{{ intellij_community_edition_download_url }}"
        target_installation_folder: "{{ intellij_community_edition_folder }}"
      tags:
        - java
        - intellij-ce
    - import_tasks: tasks/java.yml
      tags:
        - java
        - java-language
    # Python specific
    - name: Install Pycharm Ultimate
      import_tasks: tasks/jetbrains_installation.yml
      vars:
        download_url: "{{ pycharm_ultimate_download_url }}"
        target_installation_folder: "{{ pycharm_ultimate_folder }}"
      tags:
        - python
        - pycharm-ultimate
    - name: Install PyCharm Community Edition
      import_tasks: tasks/jetbrains_installation.yml
      vars:
        download_url: "{{ pycharm_community_edition_download_url }}"
        target_installation_folder: "{{ pycharm_community_edition_folder }}"
      tags:
        - python
        - pycharm-ce
    - import_tasks: tasks/python.yml
      tags:
        - python
        - python-language
    # Node
    - import_tasks: tasks/nvm.yml
      tags:
        - node
        - nvm
    # Other IDEs
    - name: Install CLion Ultimate Edition
      import_tasks: tasks/jetbrains_installation.yml
      vars:
        download_url: "{{ clion_download_url }}"
        target_installation_folder: "{{ clion_ultimate_folder }}"
      tags:
        - clion
    - import_tasks: tasks/vscode.yml
      tags: vscode
    - import_tasks: tasks/aws.yml
      tags: aws
    - name: Install Android Studio
      import_tasks: tasks/jetbrains_installation.yml
      vars:
        download_url: "{{ android_studio_download_url }}"
        target_installation_folder: "{{ android_studio_folder }}"
      tags:
        - android-studio
    # Game Dev
    - import_tasks: tasks/unity.yml
      tags: game-dev
    - import_tasks: tasks/aesprite.yml
      tags: aes
    - import_tasks: tasks/post_installation.yml
      tags:
        - default
        - post_install
