# Directories
apps_dir: "{{ ansible_env.HOME }}/apps"
binary_dir: "{{ ansible_env.HOME }}/binaries"
repos_dir: "{{ ansible_env.HOME }}/repos"
dev_machine_setup_aliases: "{{ ansible_env.HOME }}/dev-machine-setup/dotfiles/.aliases"

# ZSH
zsh_install_script_url: "https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh"

# IntelliJ
intellij_ultimate_download_url: "https://download-cdn.jetbrains.com/idea/ideaIU-2025.1.tar.gz"
intellij_ultimate_folder: "{{ apps_dir }}/intellij"

intellij_community_edition_download_url: "https://download-cdn.jetbrains.com/idea/ideaIC-2025.1.tar.gz"
intellij_community_edition_folder: "{{ apps_dir }}/intellij-ce"

# PyCharm
pycharm_ultimate_download_url: "https://download-cdn.jetbrains.com/python/pycharm-2025.1.tar.gz"
pycharm_ultimate_folder: "{{ apps_dir }}/pycharm"

pycharm_community_edition_download_url: "https://download-cdn.jetbrains.com/python/pycharm-community-2025.1.tar.gz"
pycharm_community_edition_folder: "{{ apps_dir }}/pycharm-ce"

# CLion
clion_download_url: "https://download-cdn.jetbrains.com/cpp/CLion-2025.1.tar.gz"
clion_ultimate_folder: "{{ apps_dir }}/clion"

# NVM
nvm_download_url: "https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh"

# Conda

# VSCode
vscode_download_url: "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64"

# Java
java_version: "21"

# Android Studio
android_studio_download_url: "https://r4---sn-4g5lzney.gvt1.com/edgedl/android/studio/ide-zips/2024.2.2.13/android-studio-2024.2.2.13-linux.tar.gz?met=1748885538,&mh=9o&pl=20&rms=ltu,ltu&shardbypass=sd&redirect_counter=1&cm2rm=sn-h0jld7z&rrc=80&fexp=24351658,24351662&req_id=2f8b48959c994ed1&cms_redirect=yes&cmsv=e&mip=176.199.210.25&mm=34&mn=sn-4g5lzney&ms=ltu&mt=1748885095&mv=m&mvi=4&smhost=r3---sn-4g5edndd.gvt1.com"
android_studio_folder: "{{ apps_dir }}/android-studio"
